package main;


import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.projecttoyota;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class absensi extends javax.swing.JFrame {
    
     private void kosong(){
        id_karyawan.setText(null);
        tanggal.setText(null);
        absen.setSelectedItem(null);
    }
    
     private void tampilkan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("no");
        model.addColumn("Tanggal");
        model.addColumn("ID Karyawan");
        model.addColumn("Nama");
        model.addColumn("Keterangan");
        try {
            int no = 1;
            String sql = "SELECT k.jadwal_kehadiran, k.id_karyawan, kr.nama, k.status_kehadiran FROM kehadiran k INNER JOIN karyawan kr ON k.id_karyawan=kr.id_karyawan";
            Connection con = (Connection)projecttoyota.config();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
        }
            tabel_absensi.setModel(model);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }

    /**
     * Creates new form absensi
     */
    public absensi() {
        initComponents();
        kosong();
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_karyawan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        absen = new javax.swing.JComboBox<String>();
        save = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_absensi = new javax.swing.JTable();
        tanggal = new javax.swing.JFormattedTextField();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 238, 237));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ABSENSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel2.setText("ID KARYAWAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        getContentPane().add(id_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 310, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 60, -1));

        jLabel4.setText("TANGGAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel6.setText("KETERANGAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        absen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hadir", "Izin", "Alpa" }));
        getContentPane().add(absen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 310, 30));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        tabel_absensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel_absensi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, 111));

        tanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 310, 30));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(141, 181, 150));

        menuLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/toyota_iconPutih.png"))); // NOI18N
        menuLabel.setText("MENU");
        jPanel1.add(menuLabel);

        back.setBackground(new java.awt.Color(141, 181, 150));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backclosemouseExited(evt);
            }
        });

        backLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/prev.png"))); // NOI18N
        backLabel.setText("Kembali");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelcloseLabelmouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelcloseLabelmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelcloseLabelmouseEntered1(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(backLabel)
                .addGap(116, 116, 116))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLabel)
                .addContainerGap())
        );

        jPanel1.add(back);

        close.setBackground(new java.awt.Color(141, 181, 150));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closemouseExited(evt);
            }
        });

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/exit.png"))); // NOI18N
        closeLabel.setText("Keluar");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered1(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(closeLabel)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(close);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
            // TODO add your handling code here:
            try{
                Connection con = (Connection)projecttoyota.config();
            String sql = "INSERT INTO kehadiran VALUES (?, ?, ?)";
            PreparedStatement pstm = con.prepareStatement(sql);
            
            pstm.setString(1, tanggal.getText());
            pstm.setString(2, id_karyawan.getText());
            
            String kehadiran;
            kehadiran = absen.getSelectedItem().toString();
            pstm.setString(3, kehadiran);
            
            pstm.execute();
            
            JOptionPane.showMessageDialog(null, "Berhasil Absen!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            tampilkan();
            kosong();
            
            } catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_clearActionPerformed

    private void backLabelcloseLabelmouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelcloseLabelmouseClicked
        new landingPage().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backLabelcloseLabelmouseClicked

    private void backLabelcloseLabelmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelcloseLabelmouseEntered
        // TODO add your handling code here:

        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_backLabelcloseLabelmouseEntered

    private void backLabelcloseLabelmouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelcloseLabelmouseEntered1
        // TODO add your handling code here:
        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_backLabelcloseLabelmouseEntered1

    private void backclosemouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backclosemouseExited
        // TODO add your handling code here:

        if(evt.getSource()==back){
            back.setBackground(new Color(141, 181, 150));
        }
        if(evt.getSource()==close){
            close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_backclosemouseExited

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseEntered
        // TODO add your handling code here:

        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_closeLabelmouseEntered

    private void closeLabelmouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseEntered1
        // TODO add your handling code here:
        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_closeLabelmouseEntered1

    private void closemouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closemouseExited
        // TODO add your handling code here:

        if(evt.getSource()==back){
            back.setBackground(new Color(141, 181, 150));
        }
        if(evt.getSource()==close){
            close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_closemouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> absen;
    private javax.swing.JPanel back;
    private javax.swing.JLabel backLabel;
    private javax.swing.JButton clear;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton exit;
    private javax.swing.JTextField id_karyawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel_absensi;
    private javax.swing.JFormattedTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
