package main;


import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.projecttoyota;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Barang extends javax.swing.JFrame {
    
    private void kosong(){
        id_mobil.setText(null);
        mobil.setText(null);
        tipe.setSelectedItem(null);
        warna.setText(null);
        tahun.setText(null);
        harga.setText(null);
        stok.setText(null);
    }
    
     private void tampilkan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("no");
        model.addColumn("id mobil");
        model.addColumn("mobil");
        model.addColumn("tipe");
        model.addColumn("warna");
        model.addColumn("tahun");
        model.addColumn("harga");
        model.addColumn("stok");
        
        try{
             int no = 1;
            String sql = "SELECT * from mobil";
            Connection con = (Connection)projecttoyota.config();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
            
             while(res.next()){
            model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});     
            }
             
            tabel.setModel(model);  
        }catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);  
         }
     }
    
    public Barang() throws SQLException {
        initComponents();
        tampilkan();  
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_mobil = new javax.swing.JTextField();
        mobil = new javax.swing.JTextField();
        tipe = new javax.swing.JComboBox<String>();
        warna = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        stok = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        tahun = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 238, 237));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("UNIT TERSEDIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 200, -1));

        jLabel2.setText("ID UNIT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel3.setText("NAMA UNIT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 20));

        jLabel4.setText("TIPE UNIT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 134, -1, 50));

        jLabel5.setText("WARNA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 30));

        jLabel6.setText("TAHUN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 30));

        jLabel7.setText("HARGA UNIT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 30));

        jLabel8.setText("STOCK");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        id_mobil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        id_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_mobilActionPerformed(evt);
            }
        });
        getContentPane().add(id_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 60, 330, 30));

        mobil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilActionPerformed(evt);
            }
        });
        getContentPane().add(mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 100, 330, 30));

        tipe.setForeground(new java.awt.Color(51, 51, 51));
        tipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Matic" }));
        tipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipeActionPerformed(evt);
            }
        });
        getContentPane().add(tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 330, 30));

        warna.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnaActionPerformed(evt);
            }
        });
        getContentPane().add(warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 330, 30));

        harga.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 260, 330, 30));

        update.setText("EDIT");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        save.setText("TAMBAH");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        delete.setText("HAPUS");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 440, 90));

        stok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 300, 330, 30));

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        tahun.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 330, 30));

        jPanel1.setBackground(new java.awt.Color(141, 181, 150));

        menuLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/toyota_iconPutih.png"))); // NOI18N
        menuLabel.setText("MENU");
        jPanel1.add(menuLabel);

        back.setBackground(new java.awt.Color(141, 181, 150));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backclosemouseExited(evt);
            }
        });

        backLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/prev.png"))); // NOI18N
        backLabel.setText("Kembali");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelcloseLabelmouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelcloseLabelmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelcloseLabelmouseEntered1(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(backLabel)
                .addGap(116, 116, 116))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLabel)
                .addContainerGap())
        );

        jPanel1.add(back);

        close.setBackground(new java.awt.Color(141, 181, 150));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closemouseExited(evt);
            }
        });

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/exit.png"))); // NOI18N
        closeLabel.setText("Keluar");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered1(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(closeLabel)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(close);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLabelcloseLabelmouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelcloseLabelmouseClicked
        new landingPage().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backLabelcloseLabelmouseClicked

    private void backLabelcloseLabelmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelcloseLabelmouseEntered
        // TODO add your handling code here:

        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_backLabelcloseLabelmouseEntered

    private void backLabelcloseLabelmouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelcloseLabelmouseEntered1
        // TODO add your handling code here:
        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_backLabelcloseLabelmouseEntered1

    private void backclosemouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backclosemouseExited
        // TODO add your handling code here:

        if(evt.getSource()==back){
            back.setBackground(new Color(141, 181, 150));
        }
        if(evt.getSource()==close){
            close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_backclosemouseExited

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseEntered
        // TODO add your handling code here:

        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_closeLabelmouseEntered

    private void closeLabelmouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseEntered1
        // TODO add your handling code here:
        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_closeLabelmouseEntered1

    private void closemouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closemouseExited
        // TODO add your handling code here:

        if(evt.getSource()==back){
            back.setBackground(new Color(141, 181, 150));
        }
        if(evt.getSource()==close){
            close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_closemouseExited

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tabel.rowAtPoint(evt.getPoint());
        String id = tabel.getValueAt(baris, 1).toString();
        id_mobil.setText(id);

        String Mobil = tabel.getValueAt(baris, 2).toString();
        mobil.setText(Mobil);

        String Tipe = tabel.getValueAt(baris, 3).toString();
        tipe.setSelectedItem(Tipe);

        String Warna = tabel.getValueAt(baris, 4).toString();
        warna.setText(Warna);

        String Tahun = tabel.getValueAt(baris, 5).toString();
        tahun.setText(Tahun);

        String Harga = tabel.getValueAt(baris, 6).toString();
        harga.setText(Harga);

        String Stok = tabel.getValueAt(baris, 7).toString();
        stok.setText(Stok);
    }//GEN-LAST:event_tabelMouseClicked

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM mobil WHERE mobil.id_unit='"+id_mobil.getText()+"'";
            Connection con = (Connection)projecttoyota.config();
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();

            JOptionPane.showMessageDialog(null, "Hapus Berhasil", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = (Connection)projecttoyota.config();
            String sql = "INSERT INTO mobil VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstm = con.prepareStatement(sql);

            pstm.setString(1, id_mobil.getText());
            pstm.setString(2, mobil.getText());

            String Tipe;
            Tipe = tipe.getSelectedItem().toString();
            pstm.setString(3, Tipe);

            pstm.setString(4, warna.getText());
            pstm.setString(5, tahun.getText());
            pstm.setString(6, harga.getText());
            pstm.setString(7,stok.getText());

            pstm.execute();

            JOptionPane.showMessageDialog(null, "Berhasil Tambah!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            tampilkan();
            kosong();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = (Connection)projecttoyota.config();
            String sql = "UPDATE mobil SET id_unit=?, nama_unit=?, tipe_unit=?, warna=?, tahun=?, harga_unit=?, stock_unit=? WHERE mobil.id_unit='"+id_mobil.getText()+"'";
            PreparedStatement pstm = con.prepareStatement(sql);

            pstm.setString(1, id_mobil.getText());
            pstm.setString(2, mobil.getText());

            String Tipe;
            Tipe = tipe.getSelectedItem().toString();
            pstm.setString(3, Tipe);

            pstm.setString(4, warna.getText());
            pstm.setString(5, tahun.getText());
            pstm.setString(6, harga.getText());
            pstm.setString(7, stok.getText());

            pstm.execute();

            JOptionPane.showMessageDialog(null, "Berhasil Edit!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            tampilkan();
            kosong();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampilkan();
        kosong();
    }//GEN-LAST:event_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_resetActionPerformed

    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunActionPerformed

    private void warnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warnaActionPerformed

    private void tipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipeActionPerformed

    private void mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilActionPerformed

    private void id_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_mobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Barang().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_mobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JTextField mobil;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tahun;
    private javax.swing.JComboBox<String> tipe;
    private javax.swing.JButton update;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
