/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
//import javax.swing.JPanel;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.*;
//import java.sql.Connection;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.BorderFactory;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author me
 */
public class landingPage extends javax.swing.JFrame {
//    CREATE TABLE
        DefaultTableModel model;       
        
//    ENDCREATE TABLE    
    public Connection conn;
//    public Statement stat;
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form landingPage
     */
    public landingPage() {
        
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        String []judul={"Id_Karyawan","Nama","Jenis_Kelamin","Agama","Pendidikan","No_telp","Alamat","Kode Jabatan","Jabatan"};
            model= new DefaultTableModel(judul,0);
            tableKaryawan.setModel(model);
            tampilkan();
//        String []title={"Id_Pemebeli","Nama_Pembeli","Jenis_Kel","Alamat","Nama Unit","Id Transakasi","Waktu","Id_Unit"};
//            model= new DefaultTableModel(title,0);
//            tblTransaksi.setModel(model);    
//            tampilkanTransaksi();   
    }
    
   
    
    
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("management_showroom_mobil?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        karyawanQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT k FROM Karyawan k");
        karyawanList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : karyawanQuery.getResultList();
        menu = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        employes = new javax.swing.JPanel();
        employesLabel = new javax.swing.JLabel();
        absensi = new javax.swing.JPanel();
        absensiLabel = new javax.swing.JLabel();
        unit = new javax.swing.JPanel();
        unitLabel = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        transaksiLabel = new javax.swing.JLabel();
        faktur = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        cardKaryawan = new javax.swing.JPanel();
        karyawanTitleCard = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldName = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldIdKaryawan = new javax.swing.JFormattedTextField();
        fieldJenisKel = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldAgama = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        insertBtn = new java.awt.Button();
        editBtn = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fieldHp = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldAlamat = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        deleteBtn = new java.awt.Button();
        fieldPendidikan = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldKdJabatan = new javax.swing.JFormattedTextField();
        fieldJabatan = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        btnReset = new java.awt.Button();
        scrollKaryawan = new javax.swing.JScrollPane();
        tableKaryawan = new javax.swing.JTable();
        fieldSearch = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cardTransaksi = new javax.swing.JPanel();
        transaksiPanel = new javax.swing.JPanel();
        transaksiTitle = new javax.swing.JLabel();
        labelIdPembeli = new javax.swing.JLabel();
        fieldIdPembeli = new javax.swing.JFormattedTextField();
        fieldNamaPembeli = new javax.swing.JFormattedTextField();
        labelNamaPembeli = new javax.swing.JLabel();
        fieldJnsKel = new javax.swing.JFormattedTextField();
        labelNoHpPembeli = new javax.swing.JLabel();
        labelJnsKelPembeli = new javax.swing.JLabel();
        rL = new javax.swing.JRadioButton();
        rP = new javax.swing.JRadioButton();
        fieldAlamatPembeli = new javax.swing.JFormattedTextField();
        labelAlamatPembeli = new javax.swing.JLabel();
        fieldPekerjaan = new javax.swing.JFormattedTextField();
        labelPekerjaan = new javax.swing.JLabel();
        fieldIdTransaksi = new javax.swing.JFormattedTextField();
        labelIdTransaksi = new javax.swing.JLabel();
        fieldTglTransaksi = new javax.swing.JFormattedTextField();
        labelTglTransaksi = new javax.swing.JLabel();
        fieldWaktu = new javax.swing.JFormattedTextField();
        labelWaktu = new javax.swing.JLabel();
        fieldNoFaktur = new javax.swing.JFormattedTextField();
        labelNoFaktur = new javax.swing.JLabel();
        btnTambahTransaksi = new java.awt.Button();
        btnClear = new java.awt.Button();
        scrollTableTransaksi = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(141, 181, 150));

        menuLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/toyota_iconPutih.png"))); // NOI18N
        menuLabel.setText("MENU");

        employes.setBackground(new java.awt.Color(141, 181, 150));
        employes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        employesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        employesLabel.setForeground(new java.awt.Color(255, 255, 255));
        employesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/employe_30px.png"))); // NOI18N
        employesLabel.setLabelFor(employes);
        employesLabel.setText("Karyawan");
        employesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        javax.swing.GroupLayout employesLayout = new javax.swing.GroupLayout(employes);
        employes.setLayout(employesLayout);
        employesLayout.setHorizontalGroup(
            employesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(employesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        employesLayout.setVerticalGroup(
            employesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        absensi.setBackground(new java.awt.Color(141, 181, 150));
        absensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        absensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        absensiLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        absensiLabel.setForeground(new java.awt.Color(255, 255, 255));
        absensiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/kehadiran_32px.png"))); // NOI18N
        absensiLabel.setLabelFor(absensi);
        absensiLabel.setText("Absensi");
        absensiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        javax.swing.GroupLayout absensiLayout = new javax.swing.GroupLayout(absensi);
        absensi.setLayout(absensiLayout);
        absensiLayout.setHorizontalGroup(
            absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absensiLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(absensiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        absensiLayout.setVerticalGroup(
            absensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, absensiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(absensiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        unit.setBackground(new java.awt.Color(141, 181, 150));
        unit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        unitLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unitLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/cars_32px.png"))); // NOI18N
        unitLabel.setLabelFor(unit);
        unitLabel.setText("Unit Tersedia");
        unitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        javax.swing.GroupLayout unitLayout = new javax.swing.GroupLayout(unit);
        unit.setLayout(unitLayout);
        unitLayout.setHorizontalGroup(
            unitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(unitLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        unitLayout.setVerticalGroup(
            unitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(unitLabel)
                .addContainerGap())
        );

        transaksi.setBackground(new java.awt.Color(141, 181, 150));
        transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        transaksiLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        transaksiLabel.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/transaction_32px.png"))); // NOI18N
        transaksiLabel.setLabelFor(transaksi);
        transaksiLabel.setText("Transaksi");
        transaksiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(transaksiLabel)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transaksiLabel)
                .addContainerGap())
        );

        faktur.setBackground(new java.awt.Color(141, 181, 150));
        faktur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        faktur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        close.setBackground(new java.awt.Color(141, 181, 150));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseExited(evt);
            }
        });

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/exit.png"))); // NOI18N
        closeLabel.setLabelFor(transaksi);
        closeLabel.setText("Keluar");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                landingPage.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseEntered(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout fakturLayout = new javax.swing.GroupLayout(faktur);
        faktur.setLayout(fakturLayout);
        fakturLayout.setHorizontalGroup(
            fakturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fakturLayout.setVerticalGroup(
            fakturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fakturLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(absensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(faktur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(menuLabel)
                .addGap(71, 71, 71)
                .addComponent(employes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(absensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(faktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCenter.setLayout(new java.awt.CardLayout());

        cardKaryawan.setBackground(new java.awt.Color(244, 238, 237));

        karyawanTitleCard.setBackground(new java.awt.Color(244, 238, 237));

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitle.setText("KARYAWAN");

        jPanel1.setBackground(new java.awt.Color(244, 238, 237));

        jLabel1.setText("NAMA");

        fieldName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        jLabel2.setText("ID KARYAWAN");

        fieldIdKaryawan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldIdKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdKaryawanActionPerformed(evt);
            }
        });

        fieldJenisKel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldJenisKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJenisKelActionPerformed(evt);
            }
        });

        jLabel3.setText("JENIS KEL");

        fieldAgama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAgamaActionPerformed(evt);
            }
        });

        jLabel7.setText("AGAMA");

        insertBtn.setLabel("TAMBAH");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        editBtn.setActionCommand("EDIT");
        editBtn.setLabel("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(fieldIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldJenisKel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldJenisKel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(244, 238, 237));

        jLabel4.setText("NO TLPN");

        fieldHp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHpActionPerformed(evt);
            }
        });

        jLabel5.setText("ALAMAT");

        fieldAlamat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlamatActionPerformed(evt);
            }
        });

        jLabel6.setText("KODE JABATAN");

        deleteBtn.setLabel("HAPUS");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        fieldPendidikan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldPendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPendidikanActionPerformed(evt);
            }
        });

        jLabel8.setText("PENDIDIKAN");

        fieldKdJabatan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldKdJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKdJabatanActionPerformed(evt);
            }
        });

        fieldJabatan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJabatanActionPerformed(evt);
            }
        });

        jLabel9.setText("JABATAN");

        btnReset.setLabel("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldHp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldKdJabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldHp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldKdJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout karyawanTitleCardLayout = new javax.swing.GroupLayout(karyawanTitleCard);
        karyawanTitleCard.setLayout(karyawanTitleCardLayout);
        karyawanTitleCardLayout.setHorizontalGroup(
            karyawanTitleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanTitleCardLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(labelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(karyawanTitleCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        karyawanTitleCardLayout.setVerticalGroup(
            karyawanTitleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, karyawanTitleCardLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(18, 18, 18)
                .addGroup(karyawanTitleCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKaryawanMouseClicked(evt);
            }
        });
        scrollKaryawan.setViewportView(tableKaryawan);
        if (tableKaryawan.getColumnModel().getColumnCount() > 0) {
            tableKaryawan.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tableKaryawan.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tableKaryawan.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tableKaryawan.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        fieldSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldSearchKeyPressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons_search.png"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setText("Cari Nama / ID Karyawan");

        javax.swing.GroupLayout cardKaryawanLayout = new javax.swing.GroupLayout(cardKaryawan);
        cardKaryawan.setLayout(cardKaryawanLayout);
        cardKaryawanLayout.setHorizontalGroup(
            cardKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(karyawanTitleCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollKaryawan)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardKaryawanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(cardKaryawanLayout.createSequentialGroup()
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(26, 26, 26))
        );
        cardKaryawanLayout.setVerticalGroup(
            cardKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardKaryawanLayout.createSequentialGroup()
                .addComponent(karyawanTitleCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(cardKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelCenter.add(cardKaryawan, "card2");

        cardTransaksi.setBackground(new java.awt.Color(244, 238, 237));

        transaksiPanel.setBackground(new java.awt.Color(244, 238, 237));

        transaksiTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        transaksiTitle.setText("TRANSAKSI");

        labelIdPembeli.setText("ID_PEMBELI");

        fieldIdPembeli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldIdPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdPembeliActionPerformed(evt);
            }
        });

        fieldNamaPembeli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldNamaPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaPembeliActionPerformed(evt);
            }
        });

        labelNamaPembeli.setText("NAMA PEMBELI");

        fieldJnsKel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldJnsKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJnsKelActionPerformed(evt);
            }
        });

        labelNoHpPembeli.setText("NO HP");

        labelJnsKelPembeli.setText("JENIS KELAMIN");

        rL.setText("L");

        rP.setText("P");
        rP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPActionPerformed(evt);
            }
        });

        fieldAlamatPembeli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldAlamatPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlamatPembeliActionPerformed(evt);
            }
        });

        labelAlamatPembeli.setText("ALAMAT PEMBELI");

        fieldPekerjaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPekerjaanActionPerformed(evt);
            }
        });

        labelPekerjaan.setText("PEKERJAAN");

        fieldIdTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdTransaksiActionPerformed(evt);
            }
        });

        labelIdTransaksi.setText("ID TRANSAKSI");

        fieldTglTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldTglTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTglTransaksiActionPerformed(evt);
            }
        });

        labelTglTransaksi.setText("TGL TRANSAKSI");

        fieldWaktu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWaktuActionPerformed(evt);
            }
        });

        labelWaktu.setText("WAKTU");

        fieldNoFaktur.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldNoFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoFakturActionPerformed(evt);
            }
        });

        labelNoFaktur.setText("NIK PEMBELI");

        btnTambahTransaksi.setActionCommand("TAMBAH");
        btnTambahTransaksi.setLabel("TAMBAH");

        btnClear.setActionCommand("CLEAR");
        btnClear.setLabel("CLEAR");

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(transaksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdPembeli)
                            .addComponent(labelNamaPembeli)
                            .addComponent(labelNoHpPembeli)
                            .addComponent(labelJnsKelPembeli)
                            .addComponent(labelAlamatPembeli))
                        .addGap(116, 116, 116)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldJnsKel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldIdPembeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldNamaPembeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldAlamatPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(transaksiPanelLayout.createSequentialGroup()
                                .addComponent(rL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rP))
                            .addComponent(btnTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelNoFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelIdTransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTglTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelWaktu, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(116, 116, 116)
                                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldWaktu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldIdTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldTglTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPekerjaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNoFaktur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(transaksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdPembeli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNamaPembeli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldJnsKel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNoHpPembeli)))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdTransaksi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTglTransaksi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWaktu))))
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJnsKelPembeli)
                            .addComponent(rL)
                            .addComponent(rP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAlamatPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlamatPembeli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPekerjaan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNoFaktur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        scrollTableTransaksi.setBorder(null);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTableTransaksi.setViewportView(tblTransaksi);

        javax.swing.GroupLayout cardTransaksiLayout = new javax.swing.GroupLayout(cardTransaksi);
        cardTransaksi.setLayout(cardTransaksiLayout);
        cardTransaksiLayout.setHorizontalGroup(
            cardTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTableTransaksi)
                .addContainerGap())
        );
        cardTransaksiLayout.setVerticalGroup(
            cardTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTransaksiLayout.createSequentialGroup()
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTableTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCenter.add(cardTransaksi, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        
        
        
        // TODO add your handling code here:

        if(evt.getSource()==employesLabel){
            cardKaryawan.setVisible(true);
            cardTransaksi.setVisible(false);
        }
        
         if(evt.getSource()== absensiLabel){
            new absensi().setVisible(true);
            this.dispose();
        }
         
          if(evt.getSource()==unitLabel){
            try {
                new Barang().setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(landingPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
           
            if(evt.getSource()==transaksiLabel){
            new transaksii().setVisible(true);
            this.dispose();
        }
            if(evt.getSource()==closeLabel){
            this.dispose();
        }
    }//GEN-LAST:event_mouseClicked

    private void mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered
        // TODO add your handling code here:
        if(evt.getSource()==employesLabel){
        employes.setBackground(new Color(200, 227, 197));
        }  
          if(evt.getSource()==transaksiLabel){
        transaksi.setBackground(new Color(200, 227, 197));
        }  
              if(evt.getSource()==unitLabel){
        unit.setBackground(new Color(200, 227, 197));
        }  
                if(evt.getSource()==absensiLabel){
        absensi.setBackground(new Color(200, 227, 197));
        }  
                if(evt.getSource()==closeLabel){
        close.setBackground(new Color(200, 227, 197));
        }  
    }//GEN-LAST:event_mouseEntered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        // TODO add your handling code here:
        if(evt.getSource()==employes){
        employes.setBackground(new Color(141, 181, 150));
        }  
          if(evt.getSource()==transaksi){
        transaksi.setBackground(new Color(141, 181, 150));
        }  
              if(evt.getSource()==unit){
        unit.setBackground(new Color(141, 181, 150));
        }  
                if(evt.getSource()==absensi){
        absensi.setBackground(new Color(141, 181, 150));
        }
                if(evt.getSource()==close){
        close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_mouseExited

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
//         TODO add your handling code here:
//        jFormattedTextField1ActionPerformed.setBorder(BorderFactory.createCompoundBorder(
//        jFormattedTextField1ActionPerformed.getBorder(), 
//        BorderFactory.createEmptyBorder(5, 5, 5, 5)));        
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldIdKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdKaryawanActionPerformed

    private void fieldJenisKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJenisKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJenisKelActionPerformed

    private void fieldHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHpActionPerformed

    private void fieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlamatActionPerformed

    private void fieldAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAgamaActionPerformed

    private void fieldPendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPendidikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPendidikanActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try {
            sql = "DELETE FROM karyawan WHERE id_karyawan='"+fieldIdKaryawan.getText()+"'";
            int res = stat.executeUpdate(sql);
            tampilkan();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        try {
            sql = "INSERT INTO karyawan values " + "('" + fieldIdKaryawan.getText() + "','" + fieldName.getText() + "','" + fieldJenisKel.getText() + "','" + fieldAgama.getText() + "','" + fieldPendidikan.getText() + "','" + fieldHp.getText() + "','" + fieldAlamat.getText() + "','" + fieldKdJabatan.getText()+ "')";            
            int res = stat.executeUpdate(sql);
            tampilkan();
            reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        try {
            sql = "UPDATE karyawan SET nama='"+fieldName.getText()+"',jenis_kelamin='"+fieldJenisKel.getText()+"',agama='"+fieldAgama.getText()+"',pendidikan='"+fieldPendidikan.getText()+"',no_telp='"+fieldHp.getText()+"',alamat='"+fieldAlamat.getText()+ "' WHERE id_karyawan='"+fieldIdKaryawan.getText()+"'";
            int res = stat.executeUpdate(sql);
            tampilkan();
            reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void fieldKdJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKdJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKdJabatanActionPerformed

    private void tableKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKaryawanMouseClicked
        // TODO add your handling code here:
        int i=tableKaryawan.getSelectedRow();
        if(i>-1){
           fieldIdKaryawan.setText(model.getValueAt(i, 0).toString());
           fieldName.setText(model.getValueAt(i, 1).toString());
           fieldJenisKel.setText(model.getValueAt(i, 2).toString());
           fieldAgama.setText(model.getValueAt(i, 3).toString());
           fieldPendidikan.setText(model.getValueAt(i, 4).toString());
           fieldHp.setText(model.getValueAt(i, 5).toString());
           fieldAlamat.setText(model.getValueAt(i, 6).toString());
           fieldKdJabatan.setText(model.getValueAt(i, 7).toString());
           fieldJabatan.setText(model.getValueAt(i, 8).toString());
        }
    }//GEN-LAST:event_tableKaryawanMouseClicked

    private void fieldJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJabatanActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        int row=tableKaryawan.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try {
            sql = "SELECT `id_karyawan`, `nama`, `jenis_kelamin`, `agama`, `pendidikan`, `no_telp`, `alamat`, karyawan.kd_jabatan`kd_jabatan`,`nama_jabatan` FROM `karyawan` INNER JOIN jabatann ON karyawan.kd_jabatan=jabatann.kd_jabatan WHERE nama='"+fieldSearch.getText()+"' OR id_karyawan='"+fieldSearch.getText()+"'";                           
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                model.addRow(data);
                }           
        } catch (SQLException ex) {
            Logger.getLogger(landingPage.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
        tampilkan();
    }//GEN-LAST:event_btnResetActionPerformed

    private void fieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            int row=tableKaryawan.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try {
            sql = "SELECT `id_karyawan`, `nama`, `jenis_kelamin`, `agama`, `pendidikan`, `no_telp`, `alamat`, karyawan.kd_jabatan`kd_jabatan`,`nama_jabatan` FROM `karyawan` INNER JOIN jabatann ON karyawan.kd_jabatan=jabatann.kd_jabatan WHERE nama='"+fieldSearch.getText()+"' OR id_karyawan='"+fieldSearch.getText()+"'";                           
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                model.addRow(data);
                }           
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(landingPage.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_fieldSearchKeyPressed

    private void fieldIdPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdPembeliActionPerformed

    private void fieldNamaPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaPembeliActionPerformed

    private void fieldJnsKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJnsKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJnsKelActionPerformed

    private void rPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPActionPerformed

    private void fieldAlamatPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlamatPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlamatPembeliActionPerformed

    private void fieldPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPekerjaanActionPerformed

    private void fieldIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdTransaksiActionPerformed

    private void fieldTglTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTglTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTglTransaksiActionPerformed

    private void fieldWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWaktuActionPerformed

    private void fieldNoFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoFakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNoFakturActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
//                 new koneksi().setVisible(true)
//                koneksi conn = new koneksi();
//                conn.config();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel absensi;
    private javax.swing.JLabel absensiLabel;
    private java.awt.Button btnClear;
    private java.awt.Button btnReset;
    private java.awt.Button btnTambahTransaksi;
    private javax.swing.JPanel cardKaryawan;
    private javax.swing.JPanel cardTransaksi;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeLabel;
    private java.awt.Button deleteBtn;
    private java.awt.Button editBtn;
    private javax.swing.JPanel employes;
    private javax.swing.JLabel employesLabel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel faktur;
    private javax.swing.JFormattedTextField fieldAgama;
    private javax.swing.JFormattedTextField fieldAlamat;
    private javax.swing.JFormattedTextField fieldAlamatPembeli;
    private javax.swing.JFormattedTextField fieldHp;
    private javax.swing.JFormattedTextField fieldIdKaryawan;
    private javax.swing.JFormattedTextField fieldIdPembeli;
    private javax.swing.JFormattedTextField fieldIdTransaksi;
    private javax.swing.JFormattedTextField fieldJabatan;
    private javax.swing.JFormattedTextField fieldJenisKel;
    private javax.swing.JFormattedTextField fieldJnsKel;
    private javax.swing.JFormattedTextField fieldKdJabatan;
    private javax.swing.JFormattedTextField fieldNamaPembeli;
    private javax.swing.JFormattedTextField fieldName;
    private javax.swing.JFormattedTextField fieldNoFaktur;
    private javax.swing.JFormattedTextField fieldPekerjaan;
    private javax.swing.JFormattedTextField fieldPendidikan;
    private javax.swing.JFormattedTextField fieldSearch;
    private javax.swing.JFormattedTextField fieldTglTransaksi;
    private javax.swing.JFormattedTextField fieldWaktu;
    private java.awt.Button insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.util.List<main.Karyawan> karyawanList;
    private javax.persistence.Query karyawanQuery;
    private javax.swing.JPanel karyawanTitleCard;
    private javax.swing.JLabel labelAlamatPembeli;
    private javax.swing.JLabel labelIdPembeli;
    private javax.swing.JLabel labelIdTransaksi;
    private javax.swing.JLabel labelJnsKelPembeli;
    private javax.swing.JLabel labelNamaPembeli;
    private javax.swing.JLabel labelNoFaktur;
    private javax.swing.JLabel labelNoHpPembeli;
    private javax.swing.JLabel labelPekerjaan;
    private javax.swing.JLabel labelTglTransaksi;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JRadioButton rL;
    private javax.swing.JRadioButton rP;
    private javax.swing.JScrollPane scrollKaryawan;
    private javax.swing.JScrollPane scrollTableTransaksi;
    private javax.swing.JTable tableKaryawan;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JPanel transaksi;
    private javax.swing.JLabel transaksiLabel;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JLabel transaksiTitle;
    private javax.swing.JPanel unit;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables

    
    private void reset(){
        fieldName.setText("");
        fieldKdJabatan.setText("");
        fieldJabatan.setText("");
        fieldHp.setText("");
        fieldAlamat.setText("");
        fieldIdKaryawan.setText("");
        fieldPendidikan.setText("");
        fieldAgama.setText("");
        fieldJenisKel.setText("");
    }

    void tampilkan() {
        
        int row=tableKaryawan.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try {
            sql = "SELECT `id_karyawan`, `nama`, `jenis_kelamin`, `agama`, `pendidikan`, `no_telp`, `alamat`, karyawan.kd_jabatan`kd_jabatan`,`nama_jabatan` FROM `karyawan` INNER JOIN jabatann ON karyawan.kd_jabatan=jabatann.kd_jabatan";                           
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                model.addRow(data);
        
                }           
        } catch (SQLException ex) {
            Logger.getLogger(landingPage.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
}
        
        

