/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author me
 */

public class loginForm extends javax.swing.JFrame {

    // deklarasi
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();

        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        loginIcon = new javax.swing.JLabel();
        psswrdField = new javax.swing.JPasswordField();
        psswrdIcon = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        loginField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(141, 181, 150));

        pageTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pageTitle.setForeground(new java.awt.Color(255, 255, 255));
        pageTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/login.png"))); // NOI18N
        pageTitle.setText("Sign In");

        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icon_login.png"))); // NOI18N

        psswrdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psswrdFieldActionPerformed(evt);
            }
        });
        psswrdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psswrdFieldKeyPressed(evt);
            }
        });

        psswrdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icon_password.png"))); // NOI18N

        btnLogin.setBackground(new java.awt.Color(112, 112, 112));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginDirection(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(244, 244, 244)
                                                .addComponent(pageTitle))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(199, 199, 199)
                                                .addGroup(mainPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(loginIcon)
                                                        .addComponent(psswrdIcon))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(mainPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(psswrdField, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                210, Short.MAX_VALUE)
                                                        .addComponent(loginField))))
                                .addContainerGap(216, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLogin)
                                .addGap(288, 288, 288)));
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(mainPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(loginIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 35,
                                                Short.MAX_VALUE)
                                        .addComponent(loginField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(psswrdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(psswrdIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(btnLogin)
                                .addContainerGap(161, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginDirection(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_loginDirection
        // TODO add your handling code here:

        try {
            // sql = "SELECT * FROM department WHERE
            // kd_department='"+psswrdField.getText()+"' AND
            // department='"+loginField.getText()+"'";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                String admin = "administrasi";
                if (loginField.getText().equals(rs.getString("administrasi")) == loginField.getText().equals(admin)) {
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    landingPage b = new landingPage();
                    b.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }// GEN-LAST:event_loginDirection

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_loginFieldActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_btnLoginActionPerformed

    private void psswrdFieldKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_psswrdFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                sql = "SELECT * FROM department WHERE kd_department='" + psswrdField.getText() + "' AND department='"
                        + loginField.getText() + "'";
                rs = stat.executeQuery(sql);
                if (rs.next()) {
                    String admin = "administrasi";
                    if (loginField.getText().equals(rs.getString("department")) == loginField.getText().equals(admin)) {
                        JOptionPane.showMessageDialog(null, "berhasil login");
                        landingPage b = new landingPage();
                        b.setVisible(true);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }// GEN-LAST:event_psswrdFieldKeyPressed

    private void psswrdFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_psswrdFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_psswrdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
                //// this.dispose();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JFormattedTextField loginField;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JPasswordField psswrdField;
    private javax.swing.JLabel psswrdIcon;
    // End of variables declaration//GEN-END:variables
}
