///*
////// * To change this license header, choose License Headers in Project Properties.
////// * To change this template file, choose Tools | Templates
////// * and open the template in the editor.
////// */
package main;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

///////**
////// *
////// * @author me
////// */
public class transaksii extends javax.swing.JFrame {
DefaultTableModel model;       
//    ENDCREATE TABLE    
    public Connection conn;
//    public Statement stat;
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
//
//    /**
//     * Creates new form transaksii
//     */
    public transaksii() {
        initComponents();
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        String []judul={"Id Transakasi","Waktu","Id_Unit","Id_Pemebeli","Nama_Pembeli","Jenis_Kel","Alamat","Nama Unit"};
            model= new DefaultTableModel(judul,0);
            tblTransaksi.setModel(model);
            tampilkan();   

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
**/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        back = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        transaksiPanel = new javax.swing.JPanel();
        transaksiTitle = new javax.swing.JLabel();
        fieldIdTransaksi = new javax.swing.JFormattedTextField();
        labelIdTransaksi = new javax.swing.JLabel();
        fieldTglTransaksi = new javax.swing.JFormattedTextField();
        labelTglTransaksi = new javax.swing.JLabel();
        idUnit = new javax.swing.JFormattedTextField();
        labelWaktu = new javax.swing.JLabel();
        btnTambahTransaksi = new java.awt.Button();
        hapus = new java.awt.Button();
        scroll = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        fieldIdPmbl = new javax.swing.JFormattedTextField();
        fieldNama = new javax.swing.JFormattedTextField();
        fieldHp = new javax.swing.JFormattedTextField();
        fieldAlamat = new javax.swing.JFormattedTextField();
        labelIdPembeli = new javax.swing.JLabel();
        labelNamaPembeli = new javax.swing.JLabel();
        labelNoHpPembeli = new javax.swing.JLabel();
        labelAlamatPembeli = new javax.swing.JLabel();
        fieldNIK = new javax.swing.JFormattedTextField();
        fieldPekerjaan = new javax.swing.JFormattedTextField();
        labelPekerjaan = new javax.swing.JLabel();
        labelNoFaktur = new javax.swing.JLabel();
        labelJnsKelPembeli = new javax.swing.JLabel();
        fieldJnsKelPembeli = new javax.swing.JFormattedTextField();
        fieldIdPmbl1 = new javax.swing.JFormattedTextField();
        labelIdPembeli1 = new javax.swing.JLabel();
        transaksiTitle1 = new javax.swing.JLabel();
        btnPembeli = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(141, 181, 150));

        menuLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/toyota_iconPutih.png"))); // NOI18N
        menuLabel.setText("MENU");

        transaksi.setBackground(new java.awt.Color(141, 181, 150));
        transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transaksimouseExited(evt);
            }
        });

        back.setBackground(new java.awt.Color(141, 181, 150));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closemouseExited(evt);
            }
        });

        backLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/prev.png"))); // NOI18N
        backLabel.setText("Kembali");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelmouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered1(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(backLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        close.setBackground(new java.awt.Color(141, 181, 150));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closemouseExited(evt);
            }
        });

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/exit.png"))); // NOI18N
        closeLabel.setText("Keluar");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelmouseEntered1(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(menuLabel)
                .addGap(11, 11, 11)
                .addComponent(transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        transaksiPanel.setBackground(new java.awt.Color(244, 238, 237));
        transaksiPanel.setPreferredSize(new java.awt.Dimension(1014, 598));

        transaksiTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        transaksiTitle.setText("TRANSAKSI");

        fieldIdTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdTransaksiActionPerformed(evt);
            }
        });

        labelIdTransaksi.setText("ID TRANSAKSI");

        fieldTglTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldTglTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTglTransaksiActionPerformed(evt);
            }
        });

        labelTglTransaksi.setText("TGL TRANSAKSI");

        idUnit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUnitActionPerformed(evt);
            }
        });

        labelWaktu.setText("ID UNIT");

        btnTambahTransaksi.setActionCommand("TAMBAH TRANSAKSI");
        btnTambahTransaksi.setLabel("TAMBAH TRANSAKSI");
        btnTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTransaksiActionPerformed(evt);
            }
        });

        hapus.setActionCommand("HAPUS");
        hapus.setLabel("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        scroll.setBorder(null);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        scroll.setViewportView(tblTransaksi);

        fieldIdPmbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldIdPmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdPmblActionPerformed(evt);
            }
        });

        fieldNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        fieldHp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHpActionPerformed(evt);
            }
        });

        fieldAlamat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlamatActionPerformed(evt);
            }
        });

        labelIdPembeli.setText("ID_PEMBELI");

        labelNamaPembeli.setText("NAMA PEMBELI");

        labelNoHpPembeli.setText("NO HP");

        labelAlamatPembeli.setText("ALAMAT PEMBELI");

        fieldNIK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNIKActionPerformed(evt);
            }
        });

        fieldPekerjaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPekerjaanActionPerformed(evt);
            }
        });

        labelPekerjaan.setText("PEKERJAAN");

        labelNoFaktur.setText("NIK PEMBELI");

        labelJnsKelPembeli.setText("JENIS KELAMIN");

        fieldJnsKelPembeli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldJnsKelPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJnsKelPembeliActionPerformed(evt);
            }
        });

        fieldIdPmbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldIdPmbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdPmbl1ActionPerformed(evt);
            }
        });

        labelIdPembeli1.setText("ID_PEMBELI");

        transaksiTitle1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        transaksiTitle1.setText("PEMBELI");

        btnPembeli.setLabel("ADD PEMBELI");
        btnPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(transaksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transaksiTitle1)
                .addGap(195, 195, 195))
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(transaksiPanelLayout.createSequentialGroup()
                            .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelIdTransaksi)
                                .addComponent(labelWaktu))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldIdTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transaksiPanelLayout.createSequentialGroup()
                            .addComponent(labelTglTransaksi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                            .addComponent(fieldTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(transaksiPanelLayout.createSequentialGroup()
                            .addComponent(labelIdPembeli1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldIdPmbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transaksiPanelLayout.createSequentialGroup()
                        .addComponent(labelIdPembeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldIdPmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transaksiPanelLayout.createSequentialGroup()
                                .addComponent(labelNoFaktur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(transaksiPanelLayout.createSequentialGroup()
                                .addComponent(labelPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(109, 109, 109)))
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPekerjaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNIK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addComponent(labelAlamatPembeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNamaPembeli)
                            .addComponent(labelJnsKelPembeli))
                        .addGap(119, 119, 119)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldJnsKelPembeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNoHpPembeli)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldHp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addComponent(scroll)
                .addContainerGap())
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transaksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaksiTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdTransaksi)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaPembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWaktu)
                    .addComponent(labelJnsKelPembeli)
                    .addComponent(fieldJnsKelPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTglTransaksi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdPembeli1)
                            .addComponent(fieldIdPmbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addComponent(fieldPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNoFaktur))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamatPembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdPembeli)
                    .addComponent(fieldIdPmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoHpPembeli))
                .addGap(15, 15, 15)
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 300, Short.MAX_VALUE)
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 837, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void reset(){
        fieldIdTransaksi.setText("");
        fieldTglTransaksi.setText("");
        idUnit.setText("");
        fieldIdPmbl1.setText("");
    }
        private void resett(){
        fieldIdPmbl.setText("");
        fieldNama.setText("");
        fieldHp.setText("");
        fieldNIK.setText("");
        fieldJnsKelPembeli.setText("");
        fieldAlamat.setText("");
        fieldPekerjaan.setText("");
    }
        

    
    
    private void closemouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closemouseExited
        // TODO add your handling code here:

        if(evt.getSource()==back){
            back.setBackground(new Color(141, 181, 150));
        }
        if(evt.getSource()==close){
            close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_closemouseExited

    private void closeLabelmouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseEntered1
        // TODO add your handling code here:
        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_closeLabelmouseEntered1

    private void closeLabelmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseEntered
        // TODO add your handling code here:

        if(evt.getSource()==closeLabel){
            close.setBackground(new Color(200, 227, 197));
        }
        if(evt.getSource()==backLabel){
            back.setBackground(new Color(200, 227, 197));
        }
    }//GEN-LAST:event_closeLabelmouseEntered

    private void closeLabelmouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelmouseClicked
            new landingPage().setVisible(true);
            this.dispose();
        // TODO add your handling code here:

    }//GEN-LAST:event_closeLabelmouseClicked

 
    
    private void transaksimouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksimouseExited
        // TODO add your handling code here:
        if(evt.getSource()==back){
            back.setBackground(new Color(141, 181, 150));
        }
        if(evt.getSource()==close){
            close.setBackground(new Color(141, 181, 150));
        }
    }//GEN-LAST:event_transaksimouseExited

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void btnPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembeliActionPerformed
        // TODO add your handling code here:
        try {
            sql = "INSERT INTO pembeli values " + "('" + fieldIdPmbl.getText() + "','" + fieldNama.getText() + "','" + fieldHp.getText() + "','" + fieldNIK.getText()+ "','" + fieldJnsKelPembeli.getText()+ "','" + fieldAlamat.getText()+ "','" + fieldPekerjaan.getText() + "')";
            int rs = stat.executeUpdate(sql);
            tampilkan();
            resett();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPembeliActionPerformed

    private void fieldIdPmbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdPmbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdPmbl1ActionPerformed

    private void fieldJnsKelPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJnsKelPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJnsKelPembeliActionPerformed

    private void fieldPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPekerjaanActionPerformed

    private void fieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNIKActionPerformed

    private void fieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlamatActionPerformed

    private void fieldHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHpActionPerformed

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldIdPmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdPmblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdPmblActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        int i=tblTransaksi.getSelectedRow();
        if(i>-1){
            fieldIdTransaksi.setText(model.getValueAt(i, 0).toString());
            fieldTglTransaksi.setText(model.getValueAt(i, 1).toString());
            idUnit.setText(model.getValueAt(i, 2).toString());
            fieldIdPmbl1.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            sql = "DELETE FROM transaksi WHERE id_transaksi='"+fieldIdTransaksi.getText()+"'";
            int rs = stat.executeUpdate(sql);
            tampilkan();
            reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void btnTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTransaksiActionPerformed
        // TODO add your handling code here:
        try {
            sql = "INSERT INTO transaksi values " + "('" + fieldIdTransaksi.getText() + "','" + fieldTglTransaksi.getText() + "','" + idUnit.getText() + "','" + fieldIdPmbl1.getText() + "')";
            int rs = stat.executeUpdate(sql);

            tampilkan();
            reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTambahTransaksiActionPerformed

    private void idUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUnitActionPerformed

    private void fieldTglTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTglTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTglTransaksiActionPerformed

    private void fieldIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JLabel backLabel;
    private java.awt.Button btnPembeli;
    private java.awt.Button btnTambahTransaksi;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JFormattedTextField fieldAlamat;
    private javax.swing.JFormattedTextField fieldHp;
    private javax.swing.JFormattedTextField fieldIdPmbl;
    private javax.swing.JFormattedTextField fieldIdPmbl1;
    private javax.swing.JFormattedTextField fieldIdTransaksi;
    private javax.swing.JFormattedTextField fieldJnsKelPembeli;
    private javax.swing.JFormattedTextField fieldNIK;
    private javax.swing.JFormattedTextField fieldNama;
    private javax.swing.JFormattedTextField fieldPekerjaan;
    private javax.swing.JFormattedTextField fieldTglTransaksi;
    private java.awt.Button hapus;
    private javax.swing.JFormattedTextField idUnit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlamatPembeli;
    private javax.swing.JLabel labelIdPembeli;
    private javax.swing.JLabel labelIdPembeli1;
    private javax.swing.JLabel labelIdTransaksi;
    private javax.swing.JLabel labelJnsKelPembeli;
    private javax.swing.JLabel labelNamaPembeli;
    private javax.swing.JLabel labelNoFaktur;
    private javax.swing.JLabel labelNoHpPembeli;
    private javax.swing.JLabel labelPekerjaan;
    private javax.swing.JLabel labelTglTransaksi;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JPanel transaksi;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JLabel transaksiTitle;
    private javax.swing.JLabel transaksiTitle1;
    // End of variables declaration//GEN-END:variables

    final void tampilkan() {
        
        int row=tblTransaksi.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try {
            
            sql = "SELECT id_transaksi,tgl_transaksi,mobil.id_unit,pembeli.id_pembeli,nama_pembeli,jenis_kel,alamat_pembeli,nama_unit FROM transaksi JOIN pembeli ON transaksi.id_pembeli=pembeli.id_pembeli JOIN mobil ON transaksi.id_unit=mobil.id_unit";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                model.addRow(data);
        
                }           
        } catch (SQLException ex) {
            Logger.getLogger(transaksii.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
//final void tampilkanTransaksi() {
//        
//        int row=tblTransaksi.getRowCount();
//        for(int a=0;a<row;a++){
//            model.removeRow(0);
//        }
//        try {
//            sql = "SELECT pembeli.id_pembeli,nama_pembeli,jenis_kel,alamat_pembeli,nama_unit,id_transaksi,tgl_transaksi,mobil.id_unit FROM transaksi JOIN pembeli ON transaksi.id_pembeli=pembeli.id_pembeli JOIN mobil ON transaksi.id_unit=mobil.id_unit";
//            rs = stat.executeQuery(sql);
//            while(rs.next()){
//                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
//                model.addRow(data);
//        
//                }           
//        } catch (SQLException ex) {
//            Logger.getLogger(transaksii.class.getName()).log(Level.SEVERE,null,ex);
//        }
//    }
    
}
